### ISSUE TITLE
Usage on MacOS

### ISSUE THREAD

**Issue by RamonSmit** [nicollasricas/vscode-streamdeck#1]
Hi there, 

Thanks for the awesome plugin for VSCode, Can you tell me how to enable this in MacOS? 

Thanks,
Ramon

**Comment by nicollasricas** [comment]
Hey,

There's no support for macOS at this moment. I will migrate this project to the .NET core next week, which is cross-platform so expect support very soon.

Best Regards,
Nicollas R.

**Comment by RamonSmit** [comment]
Oh! That would be fancy! Thanks alot! :smiley:

**Comment by WybeBosch** [comment]
macOs compatability would be amazing! 
seems alot of programmers that use streamdecks are on windows..

**Comment by nicollasricas** [comment]
I don't have a macOS and for some reason, my macOS VM it's not working. I've converted the project to .net core which is cross-platform.

Cold you give a try?

https://1drv.ms/u/s!Agq8DfGl4HpxiiTlMhElwYT6f-uP (Onedrive)

**Comment by WybeBosch** [comment]
You are a genius! Its working!!! 
![image](https://user-images.githubusercontent.com/40889930/75636039-8694ea00-5c1b-11ea-9470-62db7eef5e30.png)

**Comment by nicollasricas** [comment]
You should see the actions in Stream Deck after installing.

![see](https://user-images.githubusercontent.com/7860985/75636055-c7780900-5bf1-11ea-939b-13d1ebd54cd0.png)

Don't forget to install this [extension](https://marketplace.visualstudio.com/items?itemName=nicollasr.vscode-streamdeck) in VSCode or it won't work.

If everything is all right you should see this in VSCode status bar:

![image](https://user-images.githubusercontent.com/7860985/75636087-276eaf80-5bf2-11ea-81a7-81626c7dfa10.png)

**Comment by nicollasricas** [comment]
Glad it worked!

Could you please open another VSCode instance and switch between them? It should activate the one with focus, also could you share some insights about resources usage from the app? App name: com.nicollasr.streamdeckvsc.

I'm going to clean some stuff and release it at Elgato.

**Comment by WybeBosch** [comment]
Will do so when i have time tomorrow!

**Comment by WybeBosch** [comment]
- Switching between vscode windows correctly uses the active window as place where it activates the command(for example "workbench.action.togglePanel" )

All i can see of resource usage in the "Activity Monitor" for the process "com.nicollasr.streamdeckvsc" 

- is after having been turned on for the entire day
-  its at a stable 22mb for Memory, and using 10-15 threads according to the Activity Monitor.

**Comment by nicollasricas** [comment]
Please let me know if this updated version is working!

https://1drv.ms/u/s!Agq8DfGl4HpxiinUKJyb-VUaTe5W

Before you install this new version, uninstall the plugin first.

I will send this to Elgato so they can release on the official store.

**Comment by nicollasricas** [comment]
A new update, please let me know if still working, had to change some things which were requested by Elgato due to cross-platform or it won't be able to publish on the store.

I promise you it will be last time.

**DON'T FORGET TO UNINSTALL THE OLDER VERSION BEFORE INSTALL THE NEW ONE.**

https://1drv.ms/u/s!Agq8DfGl4HpxiinUKJyb-VUaTe5W?e=SCRXnE

Ty!
