### ISSUE TITLE
Supporting VS Code remote

### ISSUE THREAD

**Issue by christo-ph** [nicollasricas/vscode-streamdeck#13]
Thanks for your plugin, it is working perfectly in local projects.

Do you plan to support remote hosts as well (SSH ie)?

When I open a project which is remote, it is unable to connect.

<img width="112" alt="image" src="https://user-images.githubusercontent.com/16965068/92306358-bfc56280-ef8e-11ea-8c3e-e026f3c2139d.png">

I could see that the plugin has to be installed on the remote host as well.
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/16965068/92306344-a6241b00-ef8e-11ea-93c6-84dba4801b52.png">

I am wondering why this even is necessary, as the only communication is between the local running VSCode and Streamdeck application to send some commands.

**Comment by nicollasricas** [comment]
Hi,

Try [this](https://github.com/nicollasricas/vscode-streamdeck/issues/4#issuecomment-674471109) and let me know if it works for you.

**Comment by christo-ph** [comment]
That's dope. Thank you! Maybe add this to Quick Start Guide.
