### ISSUE TITLE
Not connecting when vscode is running on remote-ssh

### ISSUE THREAD

**Issue by soupfv** [nicollasricas/vscode-streamdeck#16]
Hi, first thanks for your awesome work !
Is there a way to use this plugin on a remote-ssh connections ?

**Comment by nicollasricas** [comment]
Hey, sorry for the late reply.

Try [this](https://github.com/nicollasricas/vscode-streamdeck/issues/4#issuecomment-674471109
) or this:

- [step 1](https://github.com/nicollasricas/vscode-streamdeck/issues/9#issuecomment-733292306)
- [step 2](https://github.com/nicollasricas/vscode-streamdeck/issues/9#issuecomment-735573820)

Let me know if it works.
