### ISSUE TITLE
Never becoming active

### ISSUE THREAD

**Issue by apedeveloper** [nicollasricas/vscode-streamdeck#17]
I've followed the steps in the readme, but my plugin never reaches the 'active' state and therefore the Stream Deck commands don't work. I've changed windows, restarted and reloaded VS Code, hardcoded the settings to the correct port, and ran the Activate command for the Stream Deck extension.  I'm running VS code on:

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0

and the latest stream deck software. 

Any ways to resolve this?

**Comment by nicollasricas** [comment]
Hi,

Are you connected through SSH or using WSL2? If so, then try [this](https://github.com/nicollasricas/vscode-streamdeck/issues/16#issuecomment-748478687) and let me know if it works.
