### ISSUE TITLE
Feature Request: Command Pipelines/Multiple Commands

### ISSUE THREAD

**Issue by bsbodden** [nicollasricas/vscode-streamdeck#18]
It would be great to be able to run short sequences of commands like:
- `workbench.action.terminal.focus`
- `workbench.action.terminal.toggleTerminal`

**Comment by nicollasricas** [comment]
Hi,

You can do that creating a multi-action on the stream deck and adding multiples commands in it.

The downside of doing this is that there no way to wait for each command execution.

If you plan to use something like the example you gave you better add a delay between commands.

On the next update which will be up in a few days, there will be support for a bulk execution that can wait for each command.

**Comment by bsbodden** [comment]
@nicollasricas thank you! Awesome work btw.
