### ISSUE TITLE
High Code Helper (Renderer) CPU Utilization

### ISSUE THREAD

**Issue by roberttoups** [nicollasricas/vscode-streamdeck#19]
On macOS BigSur (11.1) running the current version of Visual Studio Code (1.52), if the StreamDeck is not connected to the Mac (M1 Air), the Code Helper (Renderer) process begins to idle at 95%. If you disable the Stream Deck for Visual Studio Code (v4.1.5) extension, the CPU for this process immediately drops to 0.

**Comment by nicollasricas** [comment]
Hi,

My macOS VM doesn't boot anymore after a processor upgrade so could you profile the extension and send me the CPU profile?

Open the process explorer (Help -> Open Process Explorer) and look if the extension host is the one with high CPU usage.

**Start extension profile:**

![image](https://user-images.githubusercontent.com/7860985/104487085-07927100-55a3-11eb-903c-18806281c51f.png)

Find "Stream Deck for Visual Studio Code" (right-click) -> Start Extension Host Profile.

Try using some of the extension features and let the profiler record the data.

Stop the profiler and save it.

**Comment by roberttoups** [comment]
I noticed that the extension was getting errors. This might be related to my VSCode sync. My MacBook Pro is connected to the StreamDeck 99% of the time. My Air is where I am noticing this issue (have to see if the same thing happens with the Pro unconnected). VSCode settings sync added the extension to my AIr.

- Issue Type: `Bug`
- Extension Name: `vscode-streamdeck`
- Extension Version: `4.1.5`
- OS Version: `Darwin x64 20.2.0`
- VSCode version: `1.52.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 33,
		"activateCallTime": 15,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "nicollasr.vscode-streamdeck",
				"_lower": "nicollasr.vscode-streamdeck"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "WebSocket is not open: readyState 0 (CONNECTING)"
		},
		{
			"name": "Error",
			"message": "WebSocket is not open: readyState 0 (CONNECTING)"
		},
		{
			"name": "Error",
			"message": "WebSocket is not open: readyState 0 (CONNECTING)"
		}
	]
}
```

**Comment by roberttoups** [comment]
[CPU-20210113T232845.493Z.cpuprofile.txt](https://github.com/nicollasricas/vscode-streamdeck/files/5811539/CPU-20210113T232845.493Z.cpuprofile.txt)

**Comment by nicollasricas** [comment]
Thank you for sharing the CPU profile.

For some reason, it is losing the connection with the WebSocket server. Most of the time spent by the extension was reconnecting to the server.

Could you please share the extension output:
![image](https://user-images.githubusercontent.com/7860985/104539504-105f6300-55f4-11eb-9610-a4d791122482.png)

- Is the Mac Air connected through WSL or SSH?

- Are you using the default extension settings?

```
  "streamdeck.serverHost": "127.0.0.1",
  "streamdeck.serverPort": 48969
```

**Comment by roberttoups** [comment]
Thanks for the log file path. That turned the lightbulb on in my head. So I just swapped out to the M1 Air from an Intel Air. I have never installed StreamDeck yet on this M1 Air -- I did on the old Intel Air. I have VSCode settings sync turned on so Pro, Air, and PC are all in sync with VS Code. That includes extensions. So when I fired up VS Code the first time on the M1 Air, the StreamDeck extension is installed by the settings sync and I start noticing the high CPU. I will test for the same behavior on my Pro disconnected from the StreamDeck. I will open a new issue if that is the case.

**Comment by nicollasricas** [comment]
I don't see the extension or settings be synced across all your devices to be the problem I, too have everything synced.

The only thing I could think of is a problem in the WebSocket server (which is running in the Stream Deck side, that's why I asked for the log) not able to accept connections (each vscode instance).
