### ISSUE TITLE
Passing Arguments Unclear

### ISSUE THREAD

**Issue by Robert-Mattingly** [nicollasricas/vscode-streamdeck#2]
Trying to execute workbench.action.editor.changeLanguageMode and pass in the language to create language specific actions on Stream Deck.

Tried the following patterns:
workbench.action.editor.changeLanguageMode(yaml)
workbench.action.editor.changeLanguageMode('yaml')
workbench.action.editor.changeLanguageMode('(yaml)')

Would it be possible to update the README to include examples for the Execute Command task with a few patterns displaying how to pass arguments to commands?

**Comment by nicollasricas** [comment]
Hi,

That command doesn't support arguments you have to pick one language from the list although it can be done programmatically.

Next Monday I will release a new version which will support commands arguments and change language mode.

**Comment by Robert-Mattingly** [comment]
Thank you!

**Comment by nicollasricas** [comment]
Update sent to Elgato wait for them to update or download manually at [Releases](https://github.com/nicollasricas/vscode-streamdeck/releases/).

**Comment by nicollasricas** [comment]
![image](https://user-images.githubusercontent.com/7860985/70535805-12730a80-1b34-11ea-95fd-f4a6225484a5.png)

**Comment by FlorentGodin** [comment]
Hi Nicollas,

Sorry to resurect the topic. 

I would like to ask you, where could I find argument names of a command, like "snippet" for `editor.action.insertSnippet`? I'm trying to use `git.rebase` giving a branch name as an argument but I can't find any documentation in VS Code of that.

I also would like to thank you very much for that great plugin! It's awesome!

**Comment by nicollasricas** [comment]
Hey,

Usually, If I don't find it in the official documentation, I get the command ID and search on the repository issues or through the source code.

Best

**Comment by FlorentGodin** [comment]
Hey Nicollas,

Sorry for my late message.

Thank you for your answer! I didn't find what I was looking for in the source code (it might be not possible right now). Maybe it could be an idea to gradually reference these arguments somewhere ?

Thanks again for your work on this extension, I use it everyday!

Best

**Comment by nicollasricas** [comment]
> Hey Nicollas,
> 
> Sorry for my late message.
> 
> Thank you for your answer! I didn't find what I was looking for in the source code (it might be not possible right now). Maybe it could be an idea to gradually reference these arguments somewhere ?
> 
> Thanks again for your work on this extension, I use it everyday!
> 
> Best

Couldn't you achieve this using the terminal command? It does support multi-action as well.

I don't know what are you trying to achieve but take a look at this: [https://git-scm.com/docs/git-rebase](https://git-scm.com/docs/git-rebase).

Also, take a look at this:
[https://github.com/nicollasricas/vscode-deck/issues/41#issuecomment-1081772820](https://github.com/nicollasricas/vscode-deck/issues/41#issuecomment-1081772820).

Hope it helps,
Best.
Nicollas R.
