### ISSUE TITLE
Document WebSocket messages

### ISSUE THREAD

**Issue by theS1LV3R** [nicollasricas/vscode-streamdeck#20]
Hey!

I am trying to develop a client for this extension for use with [Bitfocus Companion](https://bitfocus.io/companion), but I am not sure how the WebSocket is designed.

It would be awesome if all messages, properties, headers, etc. could be documented to allow for other people to create clients more easily.

**Comment by nicollasricas** [comment]
Hi,

Could you share more info about what are you trying to achieve? The plugin on the stream deck side have a websocket server and accept each vscode instance as a connection.

Each connection has its ID, and that's how I can filter to which vscode instance (websocket clients) should send the messages (whenever the user press a key).

**Comment by theS1LV3R** [comment]
I'm basically trying to recreate the StreamDeck plugin, but for companion instead of the Elgato StreamDeck program. There are no docs anywhere i could find that documents the communication between VSCode and the StreamDeck plugin over WSS, so it's really hard to recreate.

**Comment by nicollasricas** [comment]
The project were divided into two repositories (which I find very annoying, but when the idea started I built one at the time and i'm lazy to put them together).

The communication it's quite simple, so just take a look at the two repositories and you will be fine.

If you need any assistant send me a ping and I will try to help you.

vscode extension - [https://github.com/nicollasricas/vscode-streamdeck](https://github.com/nicollasricas/vscode-streamdeck)
stream deck plugin - [https://github.com/nicollasricas/streamdeckvsc](https://github.com/nicollasricas/streamdeckvsc)

**Comment by nicollasricas** [comment]
Maybe I misunderstood it, do you wish to integrate my plugin with your companion app?

If that's the case, I don't see how this could work. Unless, if there's a way to send data from a client to another client.

**Comment by theS1LV3R** [comment]
I was mainly thinking of docs that document the communication between the VSCode plugin and the Stream Deck plugin, like what messages are sent, what params, types, etc.

**Comment by nicollasricas** [comment]
Then just looking at both repositories you will be able to implement it.

Since each side sends/receives messages, they don't know anything about the other side execution.

Each message is just a simple class converted to a string JSON.

**Comment by nicollasricas** [comment]
Eg.::

- Execute command message (stream deck side):  https://github.com/nicollasricas/streamdeckvsc/blob/master/StreamDeckVSC/Messages/ExecuteCommandMessage.cs

- Execute command message (vscode side): https://github.com/nicollasricas/vscode-streamdeck/blob/master/src/messages/executeCommandMessage.ts

- How the "execute command" is sent (stream deck side): https://github.com/nicollasricas/streamdeckvsc/blob/master/StreamDeckVSC/Keys/ExecuteCommandKey.cs

- How it is received (vscode side):  https://github.com/nicollasricas/vscode-streamdeck/blob/master/src/extension.ts#L124
