### ISSUE TITLE
Is it possible to use this extension with Touch Portal?

### ISSUE THREAD

**Issue by robert-taylor-maersk** [nicollasricas/vscode-streamdeck#23]
Touch Portal is an iOS/Android app that allows you to re-purpose an old phone or tablet into a stream deck. It makes a great cheap alternative to the Elgato Stream Deck (16 buttons for free, or up to 110 per page if you purchase the app).

Because Touch Portal supports HTTP POST and GET actions, I wondered whether it would be possible to get it to talk to this extension? I'm assuming the extension just accepts JSON formatted requests on the configured address & port, but there is nothing in the readme that relates to the expected message format. 

Any advice would be appreciated :)

**Comment by robert-taylor-maersk** [comment]
Now I've found the repository for the stream-deck side - so that will help!

vscode extension - https://github.com/nicollasricas/vscode-streamdeck
stream deck plugin - https://github.com/nicollasricas/streamdeckvsc

**Comment by nicollasricas** [comment]
If you need help with anything let me know. I was planning to do a mobile version using Stream Deck mobile API (if there's one or using Touch Portal) after releasing the new version.

**Comment by robert-taylor-maersk** [comment]
Supporting Touch Portal would be awesome! 
I'm was planning take a look in my spare time to see if there was a way to adapt your existing code - however my JS/TS experience is very limited and I've not looked into writing VS Code extensions before. So at the moment I was just investigating possibilities
