### ISSUE TITLE
Feature Request: Deactivate StreamDeck  / Project Selection via Port

### ISSUE THREAD

**Issue by eungbean** [nicollasricas/vscode-streamdeck#25]
Thank you for great project!
This brought my programming experience to a higher level.

I'm a deep learning researcher, and I open several projects at once at the same time.
The problem here is that every time I run Debug, debugging goes on all projects simultaneously.
This is a terrible thing.
Therefore, the functions I want are as follows.

* function to specify Project
* function to temporarily disable StreamDeck in a project.

Simple solutions may include:
* Assign {projectName:Port} for each project
* (VSCode) cmd (ctrl) + Shift + P > Stream Deck : Select Project (Port)
or
* (VSCode) cmd (ctrl) + Shift + P > Stream Deck : Deactivate

What do you think about this idea?
Thank you!

**Comment by nicollasricas** [comment]
Hi,

When you run Debug both instances were active? Only the active session (instance) should receive the command whenever you press an action key.

![image](https://user-images.githubusercontent.com/7860985/110813369-d2329880-825e-11eb-83bb-645813279fd4.png)

Are you using the MAC version?

**Comment by eungbean** [comment]
Yes, I'm using a Mac. 
I tried pressing that button, but the connection is not deactivated. 
The redirect continues to run.

**Comment by nicollasricas** [comment]
Some of the features you suggested I already plan to implement although they shouldn't be needed at all if session activation were working.

Could you provide the plugin log and the extension output from both instances?

Plugin.log location:
`~/Library/Application Support/com.elgato.StreamDeck/Plugins/com.nicollasr.streamdeckvsc.mac.sdPlugin/plugin.log`

Extension output:
![image](https://user-images.githubusercontent.com/7860985/111461693-e90c3b80-86f3-11eb-8f19-9eeb211726d5.png)
