### ISSUE TITLE
"Execute Command" help to fill Arguments (JSON) for SSH connection label:"help wanted" 

### ISSUE THREAD

**Issue by Metus88** [nicollasricas/vscode-streamdeck#31]
I would like to press a button in my stream deck to:
1) Open visual studio code 
2) Connecto to my raspberry through SSH connection

I follow the instructions and my visual studio code and stream deck are linked!
I also find the Command ID:  "oopensshremotes.openEmptyWindowInCurrentWindow"
It works but I have to insert all information like user and ip/host and password. (So I thought that using Arguments (JSON) I can fill automatically all the fields).
I read this [link](https://code.visualstudio.com/docs/remote/ssh) and maybe this part can help me... but I'm not good to solve my problem:
```
Host remotehost.yourcompany.com
    User yourname
    HostName another-host-fqdn-or-ip-goes-here
    IdentityFile ~/.ssh/id_rsa-remote-ssh
```
Someone can help me? Thanks

**Comment by nicollasricas** [comment]
Hi,

Try to create an action like the one below and let me know if that works.

![image](https://user-images.githubusercontent.com/7860985/121888505-14e49080-cce6-11eb-8239-c37073650155.png)

`Command (ID):` `vscode.newWindow`

Arguments  (JSON):

```json
{
  "reuseWindow": true,
  "remoteAuthority": "ssh-remote+<hostname>"
}
```

**Comment by Metus88** [comment]
it works! thanks. Can you tell me how you discover that syntax?
```
 {
  "reuseWindow": true,
  "remoteAuthority": "ssh-remote+<hostname>"
}
```
and there is a way to set a path of ssh? and compile automatically the password? My goal is to go to my raspberry 192.168.X.XXX but I would like to go directly in this path "/home/homeassistant/.homeassistant"

Before you send me the answer I did a multi-action but it is not very smart and robust. 
![image](https://user-images.githubusercontent.com/48072890/121889543-a7525780-cd19-11eb-8452-2fdad11c96a8.png)

**Comment by nicollasricas** [comment]
I found out through the source files there's a lot of commands that support arguments but isn't documented yet.

I think you can add the user and password like this:
host@user@password

**Comment by nicollasricas** [comment]
Unfortunately, I didn't find out the source code for the command `opensshremotes.openEmptyWindowInCurrentWindow`.

The SSH feature has a lot of extensions beneath it and I couldn't find any of these extensions source code. They all have the same repository source which is [https://github.com/microsoft/vscode-remote-release](https://github.com/microsoft/vscode-remote-release)

**Comment by nicollasricas** [comment]
It appears that you can set the ssh config file with [multiple hosts](https://unix.stackexchange.com/questions/61655/multiple-similar-entries-in-ssh-config) and then use the "ssh-remote+ALIAS_NAME" to connect.

> ```
> Host My Raspberry (ALIAS_NAME)
>     User yourname
>     HostName host
>     IdentityFile ....
>
> Host My Arduino (ALIAS_NAME)
>     User yourname
>     HostName host
>     IdentityFile ....
> ```

**Comment by Metus88** [comment]
very cool information! I edited my config file calling it with the alias... but I'm still not able to insert the password and insert the path: "/home/homeassistant/.homeassistant"

I'm working on it

FYI: ` host@user@password ` doesn't work

**Comment by nicollasricas** [comment]
Your password "goes under" the `IdentityFile` which is a key. It's not that hard to create one.

- https://docs.rightscale.com/faq/How_Do_I_Generate_My_Own_SSH_Key_Pair.html
- https://confluence.atlassian.com/bitbucketserver/creating-ssh-keys-776639788.html
- https://git-scm.com/book/pt-pt/v2/Git-no-Servidor-Generating-Your-SSH-Public-Key

Try to create a multi-action that connects to the SSH and then use the "Open Folder" action with the path: `/home/homeassistant/.homeassistant`.

**Comment by Metus88** [comment]
thanks a lot.
1) I know about the key but I tried with easy password. However I will create one. So thanks again.
2) I will create a multi-action to go /home/homeassistant/.homeassistant
Thanks a lot. you solve it!
