### ISSUE TITLE
❓ Is there a streamdeck config for debugging in vscode ?

### ISSUE THREAD

**Issue by cognominal** [nicollasricas/vscode-streamdeck#32]
Will receive the deck tomorrow. I would like to use it right away without learning the API.
Someone must have already done it.

**Comment by nicollasricas** [comment]
There's not much to learn besides finding the commands IDs on the vscode and creating actions in your stream deck.

Make sure you read the Getting Started after installation and you are good to go.

If you need further assistance let me know.
