### ISSUE TITLE
Feature Request: Support WSL2 paths for Open Folder

### ISSUE THREAD

**Issue by meenie** [nicollasricas/vscode-streamdeck#34]
As the title says.  I don't want to use the network path because then it doesn't run vs code within WSL.  From powershell, you can run this command to do it: `code -n --folder-uri=vscode-remote://wsl+Ubuntu/home/meenie/dev-project`

**Comment by nicollasricas** [comment]
Hey,

Did you try adding the full path to the "open folder" action? It should work.

![image](https://user-images.githubusercontent.com/7860985/140534344-53a9f910-8863-4983-9ff8-e22765d31133.png)

**Comment by proximix** [comment]
Can you expand on this?  This doesn't seem to be working for me. I am putting this in the path:  \\wsl.localhost\Ubuntu-22.04\home\username\code\

If I try to add vscode-remote://  it says the location does not exist.

It opens up but doesn't up on in a WSL session.

**Comment by proximix** [comment]
Am I missing something here?  I am putting \\wsl.localhost\Ubuntu-22.04\home\username\code\work in my path but it just opens up in a non WSL window like meenie said.  How do you get this to open a folder in a WSL window?
