### ISSUE TITLE
Feature Request: Set to active on most foreground window/active window

### ISSUE THREAD

**Issue by cjlawson02** [nicollasricas/vscode-streamdeck#39]
I believe this would be done by monitoring something similar to how browsers do this:

`document.addEventListener("visibilitychange", onchange);`

**Comment by nicollasricas** [comment]
Hey,

There's already an implementation for that. Whenever you switch instances, it should activate the focused one.

You can click on the status bar or switch tabs again to force the activation.

Take a look at these issues (#7, #25) for more information.

If the issue persists, attach the extension output here.

Best,
Nicollas R.
