### ISSUE TITLE
appsettings.json not existing - using Plugin on VS Code Remote Server

### ISSUE THREAD

**Issue by lukas-runge** [nicollasricas/vscode-streamdeck#4]
Please add an example appsettings.json file to the repo so I am actually able to configure and use your beautiful plugin. Thanks!

Kind regards
Lukas

**Comment by nicollasricas** [comment]
Please make sure you have both the Stream Deck plugin and the Visual Studio Code extension installed as mentioned [here](https://github.com/nicollasricas/vscode-streamdeck#getting-started)!

I've updated the README file.

Let me know if it works.

Thanks for reporting.

**Comment by rettgerst** [comment]
similar issue here except that my host is not publicly available on the internet (nor do I want it to be), I connect using an ssh multi-hop connection. would it be possible to configure the plugin to connect over ssh instead of http? or better yet, make the VSCode extension a UI extension instead of a Workspace extension?

**Comment by nicollasricas** [comment]
There's no need to be public on the internet you can use your local IP, without any problems.

The extension already works with multiple workspaces and doesn't need an opened one to work.

On the Stream Deck side, the WebSocket server registers all opened instances of VS Code and them, decide to which one it should send the command.

On the VS Code side, each opened instance connects to the server allowing the tracking process.

So you should change the "streamdeck.serverHost" setting and point to the IP of the machine that has the Stream Deck connected to the USB port. That machine will be the host and the VS code instances will connect to them, doesn't matter if they are remote or not as long they can access the same network level you should be fine.

**Comment by rettgerst** [comment]
my problem is that my host and client are not on the same network, so the VSCode extension running on another machine, in another building, on a different network, cannot see the deck plugin's server running on the local machine.

but fortunately I found a solution. I added this line to my .ssh/config alias:

`RemoteForward 48969 127.0.0.1:48969`

this forwards the port on the remote machine to tunnel back to my local machine through the same ssh connection, allowing the VSCode plugin on the remote to connect to the Stream Deck plugin.

maybe you can add this to the readme to help other remote plugin users.
