### ISSUE TITLE
Reference active file in terminal command

### ISSUE THREAD

**Issue by Petah** [nicollasricas/vscode-streamdeck#41]
Hi, how do I reference the active file in terminal command?

Something like `echo ${file}`

**Comment by WouterNoordhof** [comment]
I was wondering the same, I'm trying to run test classes of the currently opened file, but if I use the ${fileBasename} in the terminal command, it doesn't use the variable, but instead just prints '${fileBasename}'

**Comment by Petah** [comment]
Yea I didn't figure it out. But I worked around it by using the command runner plugin, and binding a command to a hotkey, then used the Stream Deck to trigger the hotkey.

https://marketplace.visualstudio.com/items?itemName=edonet.vscode-command-runner

**Comment by nicollasricas** [comment]
Hey,

I've looked in the documentation and source and couldn't find how you could do that, except for sending a sequence to the terminal.

What you could do is:
Create an action where the command ID is the send sequence to the terminal, and the arguments are the command itself with the supported variables.

Send sequence example:
[https://code.visualstudio.com/docs/editor/integrated-terminal#_send-text-via-a-keybinding](https://code.visualstudio.com/docs/editor/integrated-terminal#_send-text-via-a-keybinding)

Supported variables:
[https://code.visualstudio.com/docs/editor/variables-reference](https://code.visualstudio.com/docs/editor/variables-reference)

![image](https://user-images.githubusercontent.com/7860985/160604482-1bbd36e9-a564-4322-af7e-a06885f8b688.png)

```json
{
    "text": "npm run fix-my-file ${file} \r"
}
```
`\r` or `\u000D` as a return
