### ISSUE TITLE
Cannot load 4.1.6

### ISSUE THREAD

**Issue by 0x1ad2** [nicollasricas/vscode-streamdeck#42]
Hi @nicollasricas 👋🏼 

When I use version **4.1.6** it of the extension it doesn't load at all, I cannot activate either reconnect the stream deck to my VS code instance. Downgrading to **4.1.5** helped getting the `Deck | Connected | Active` visible in the status bar again.

Is there any way I can help you getting a stable version?

**Comment by nicollasricas** [comment]
Hi,

If the extension doesn't load them, toggle the extension developer tools (Help ⇾ Toggle Developer Tools) and look at the console, It should have an error activating the extension.

If not, then let me know, so we could investigate it further.

Best,
Nicollas

**Comment by nicollasricas** [comment]
Please share the logs from the following locations as well:

View → Open View → Log (Shared)
View → Open View → Log (Window)
View → Open View → Log (Extension Host)
View → Command Palette → Toggle Shared Process → Console
