### ISSUE TITLE
How to create custom triggers?

### ISSUE THREAD

**Issue by eluce2** [nicollasricas/vscode-streamdeck#48]
I have been looking into BetterTouchTool to control my stream deck instead of the Native Stream Deck software. I'm wondering if it would be possible to document and expose an endpoint such that I could send commands directly to the VSCode extension via URL or similar, so it could be triggered outside of the stream deck plugin.\

It looks like you're using websockets so maybe this isn't an easy ask, but I'd be curious if you have other ideas for this use case.

**Comment by nicollasricas** [comment]
Based on the BetterTouchTool [documentation](https://docs.folivora.ai/docs/1300_stream_deck.html) the `mode 2` will allow creating an identifier/proxy for original Stream Deck actions, which means that any kind of action and custom plugins will be supported by default.

As for `mode 1` I added to the backlog, so this may be released after the next major update (6.0).

Going to close this one for now.
