### ISSUE TITLE
This plugin is a zombie that cannot be killed.

### ISSUE THREAD

**Issue by romanr** [nicollasricas/vscode-streamdeck#49]
After being uninstalled it still starts again with Streamdeck. 
I tried reinstall and then immediately uninstalled, after that it looked like it's gone, not running. Then after Streamdeck self-update the process appeared again.
On top of everything it's only Intel architecture.

<img width="762" alt="image" src="https://github.com/nicollasricas/vscode-deck/assets/329079/03c9746d-1cf4-431f-9e9f-eb69832c2a45">

**Comment by nicollasricas** [comment]
I don't have any control over the installation, uninstallation, and the update process. Elgato does!

Also, there isn't any kind of hook/injection we do to load custom plugins… The Stream Deck software load each one (the executables ones) to the process tree so everything is controlled by the software itself. If you kill the main process everything inside the tree will be closed as well.

If you keep having those issues, report it to Elgato.
