### ISSUE TITLE
Execute Command: Command (ID) disappears after changing focus out of button

### ISSUE THREAD

**Issue by coreycauble** [nicollasricas/vscode-streamdeck#5]
I am in the Stream Deck Config App on MacOs 10.15.1
I am using the Execute Command Button Type after pasting the Command Id I want, then moving to another button config all config options for the button disappear except the Title.
![Screenshot 2020-04-17 11 58 19](https://user-images.githubusercontent.com/1545810/79589090-daac3e80-80a2-11ea-971a-b44da31902b6.png)
![Screenshot 2020-04-17 11 58 37](https://user-images.githubusercontent.com/1545810/79589093-dbdd6b80-80a2-11ea-985b-5bdadd3e01c2.png)

Thanks for the plugin hope to be using it soon.

**Comment by nicollasricas** [comment]
Hey,

Could you send me the log file and:
- Software version:
- Firmware version:
- Plugin version:

Log file location:
Windows:
`%appdata%\Elgato\StreamDeck\Plugins\com.nicollasr.streamdeckvsc.sdPlugin\pluginlog.log`

Mac:
`~/Library/Application Support/com.elgato.StreamDeck/Plugins/com.nicollasr.streamdeckvsc.mac.sdPlugin/pluginlog.log`
