### ISSUE TITLE
Running a task from tasks.json

### ISSUE THREAD

**Issue by colaholicu** [nicollasricas/vscode-streamdeck#52]
Is there a way to run a task from tasks.json? Not the default run/build task, but rather one like "MyTask" in the example below:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "MyTask",
            "type": "shell",
            "command": "${workspaceFolder}/mytask.bat",
            "problemMatcher": [],
            "group": "build",
            "args": [
                "--only-update",
                "${input:package}",
            ]
        },
}
```

**Comment by AlexisHartford** [comment]
Use Execute Command and set 
Command ID: 
`workbench.action.tasks.runTask`
And
Arguments (JSON):
```
{
    "task": "MyTask"
}
```
Example of how i did it.
![image_2024-03-26_065502750](https://github.com/nicollasricas/vscode-deck/assets/12422656/429fb8c5-ed5d-41e9-a101-6a77782ae78d)

**Comment by colaholicu** [comment]
Thank you so much! I imagined I was missing something basic :)
