### ISSUE TITLE
No "Active"

### ISSUE THREAD

**Issue by Ajwah** [nicollasricas/vscode-streamdeck#7]
I have only one window open. When starting up Visual Studio Code, it states: `Deck | Connecting` and shortly afterwards it changes to `Deck | Connected` 
It never states `Active` regardless as to me restarting Visual Studio Code several times or me opening several windows and cycling through them using `tab`.

<img width="183" alt="Screen Shot 2020-05-01 at 4 30 09 PM" src="https://user-images.githubusercontent.com/11848116/80839326-06faab80-8bc9-11ea-9b07-d07fd49ff6dd.png">

You may find all relevant information about my system etc as posted in [this issue](https://github.com/nicollasricas/vscode-streamdeck/issues/6)

**Comment by nicollasricas** [comment]
Wich OS are you using? macOS?

What plugin version are you using (stream deck side)?
> Open Stream Deck -> More Actions -> Visual Studio Code

What extension version you have installed? (vscode side)?

Try click in the status bar item that says "Deck | Connected" it will force the activation, then send me the extension Output here.

![image](https://user-images.githubusercontent.com/7860985/80844576-fa7c5000-8bd4-11ea-9557-fcf4c09e0081.png)

**Comment by Ajwah** [comment]
> Wich OS are you using? macOS?
Yes

> What plugin version are you using (stream deck side)?
<img width="824" alt="Screen Shot 2020-05-02 at 4 36 26 PM" src="https://user-images.githubusercontent.com/11848116/80891606-1514fe80-8c93-11ea-9c36-65063dceec6c.png">

> What extension version you have installed? (vscode side)?
<img width="1255" alt="Screen Shot 2020-05-02 at 4 37 30 PM" src="https://user-images.githubusercontent.com/11848116/80891628-3970db00-8c93-11ea-8118-314d6954be65.png">

> Try click in the status bar item that says "Deck | Connected" it will force the activation, then send me the extension Output here.
<img width="1248" alt="Screen Shot 2020-05-02 at 4 41 04 PM" src="https://user-images.githubusercontent.com/11848116/80891701-b8661380-8c93-11ea-8599-09a912724824.png">

**Comment by nicollasricas** [comment]
Hey,

Could you try with this? After I upgrade my processor for some reason my macOS VM doesn't boot so I can't test it also send me the info shown at Help -> About (in VS Code).

Sorry for the amount of information that I've requested. I had the logger in the extension disable due to a change that I was doing it.

[Install from a VSIX](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix)

[vscode-streamdeck-3.1.6.zip](https://github.com/nicollasricas/vscode-streamdeck/files/4574748/vscode-streamdeck-3.1.6.zip)

**Comment by Ajwah** [comment]
This is the output:
```
Connecting to Stream Deck
Registering session d66b5586-33a2-44e5-bfa8-4ee8861b61791588629094315
Connected to Stream Deck.
[5/4/2020, 5:51:43 PM] Activation requested to d66b5586-33a2-44e5-bfa8-4ee8861b61791588629094315
[5/4/2020, 5:51:43 PM] Activation requested to d66b5586-33a2-44e5-bfa8-4ee8861b61791588629094315
[5/4/2020, 5:51:44 PM] Activation requested to d66b5586-33a2-44e5-bfa8-4ee8861b61791588629094315
[5/4/2020, 5:51:44 PM] Activation requested to d66b5586-33a2-44e5-bfa8-4ee8861b61791588629094315
[5/4/2020, 5:51:44 PM] Activation requested to d66b5586-33a2-44e5-bfa8-4ee8861b61791588629094315
[5/4/2020, 5:51:44 PM] Activation requested to d66b5586-33a2-44e5-bfa8-4ee8861b61791588629094315
[5/4/2020, 5:51:45 PM] Activation requested to d66b5586-33a2-44e5-bfa8-4ee8861b61791588629094315
[5/4/2020, 5:51:45 PM] Activation requested to d66b5586-33a2-44e5-bfa8-4ee8861b61791588629094315
[5/4/2020, 5:51:45 PM] Activation requested to d66b5586-33a2-44e5-bfa8-4ee8861b61791588629094315
[5/4/2020, 5:52:01 PM] Activation requested to d66b5586-33a2-44e5-bfa8-4ee8861b61791588629094315
```

**Comment by nicollasricas** [comment]
How is your "settings.ini" now? The file was already there, if yes, it was empty? For some reason, Config.NET wasn't able to use the default values on macOS. I will report to them.

I will release an official version tomorrow.

Thank you for your help.

**Comment by Ajwah** [comment]
The file was not there. I had to create it.

**Comment by timswilson** [comment]
Hi, I have the same issue as @Ajwah. I am showing Deck | Connected in the status bar. When I click Deck | Connected I do not see any output except for "Connecting to Stream Deck, Connected to Stream Deck.".

I navigated to where the settings.ini file should be (macOS) and found that it wasn't their either. I created an empty file, but found it still wouldn't activate/connect. Should I put some values in the file to get it to connect? The "You can change the IP and port to the message server in the settings.ini file." is a little over my head 🤓. 

Thanks for the plugin by the way, I absolutely love it.

**Comment by nicollasricas** [comment]
Hi,

As reported by @Ajwah  for some reason, the Config DLL can't deal with the default values on macOS.

Try to add the values into settings.ini manually.

It should look like this:
[general]
host=127.0.0.1
port=48969

Let me know if this works!

**Comment by timswilson** [comment]
@nicollasricas, thanks, that fixed it for me. My bad, I should have just tried the example host and port that you had in the instructions. Now I see where I can choose my own and update it in the extension settings. 

Again I really appreciate this extension 🤜.
