### ISSUE TITLE
vscode.openFolder-Command not working

### ISSUE THREAD

**Issue by Gamebomb** [nicollasricas/vscode-streamdeck#8]
Hello,
I have a little problem with the "Execute Command"-module in your plugin for Elgato Stream Deck.

**Short explaination:**
I use different profiles based on the program which is in the foreground. I want to open different folders (or projects) with one button. In a detailed research I found out in the api docs Visual Studio Code provides the command _vscode.openFolder_ with the two arguments _uri_ and _newWindow_. I tested some code but the folder won't open without any error message.

Do you have an idea what the problem is?
I attached some screenshots to get a better view on that problem ;).

Thanks in advance!

Images:
![image](https://user-images.githubusercontent.com/15615088/82816331-40a69580-9e9b-11ea-85f3-e018d7370f0d.png)
![image](https://user-images.githubusercontent.com/15615088/82816519-95e2a700-9e9b-11ea-99b9-b2af83faa631.png)
![image](https://user-images.githubusercontent.com/15615088/82816705-ef4ad600-9e9b-11ea-997e-6ede8ebda9b1.png)

**Software Version:**
Stream Deck: 4.7.0.12981
Firmware: 1.0.191203
Plugin: 4.1.3

**Comment by nicollasricas** [comment]
Hey,

Unfortunately, the "vscode.openFolder" command doesn't support JSON as arguments.

I could change the plugin to accept a string comma-separated values and parse it, but it won't work either since the path expected is URI and not a string.

I had investigated the source code and couldn't find a way to do this in a generic way that allows use in multiple cases.

If you have any idea, please let me know.

**Comment by nicollasricas** [comment]
![image](https://user-images.githubusercontent.com/7860985/83035627-b0d22a00-a007-11ea-8927-c693c0e94b0d.png)

Will be released later today.

**Comment by Gamebomb** [comment]
Hi,
I think a new action is a very good option to solve that problem. It is very usefull if I can switch the projects with one button on my Elgato Stream Deck.
I will wait for the new update. Thank you very much for the quick help.

Have a nice day ;).

**Comment by nicollasricas** [comment]
Hey,

Just released the new update. You can download the latest version at [Releases ](https://github.com/nicollasricas/vscode-streamdeck/releases/latest)or wait until Elgato update on the store.
